# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_maintenancenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancenotice',
            name='title',
            field=models.TextField(default=b'Maintenance Information'),
        ),
    ]
