# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_preferences_update_troposphere_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemetadata',
            name='site_footer',
            field=models.TextField(default=b'', blank=True, help_text=b'Full-text HTML replacement of footer to host installation organization or product page.'),
        ),
    ]
