# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-17 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sitemetadata_site_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemetadata',
            name='external_allocation_help_link',
            field=models.CharField(blank=True, default=b'', help_text=b"Hyperlink to a site's external allocation policy.", max_length=254),
        ),
    ]
