# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 23:13
from __future__ import unicode_literals

from django.db import migrations, models

def invert_login_field(apps, schema_editor):
    MaintenanceRecord = apps.get_model("api", "MaintenanceRecord")
    for record in MaintenanceRecord.objects.all():
        # the logic of "allowing" versuses "disableing" means that
        # the older record fields are indicating the _opposite_ of
        # the new field, so we "invert" the boolean, and move on.
        record.disable_login = not record.disable_login
        record.save()


def no_op(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_sitemetadata_external_allocation_help_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='allow_login',
            new_name='disable_login',
        ),
        migrations.RunPython(
            invert_login_field,
            no_op),
    ]
