# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_maintenancerecord_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='allow_ssh_hyperlinks',
            field=models.BooleanField(default=False),
        ),
    ]
