#!/bin/bash
set -e

get_files() {
    git diff --cached --name-only --diff-filter=ACM | grep -E .jsx?$
}

for f in `get_files`; do
    # Cat files as they exist in the index
    git show :$f
done | npm run lint-pre-commit --silent
